#!/usr/bin/env python3
"""Refreshes lib/src/bitchat/geo_relays.g.dart from bitchat's relay list.

bitchat publishes and reads each geohash channel on the relays nearest the
cell, from this list; Conest's gateway uses the same list so both pick the
same relays. The app also fetches the list itself; this copy is the
fallback when it cannot.
"""
import pathlib
import urllib.request

SOURCE = (
    'https://raw.githubusercontent.com/permissionlesstech/bitchat/refs/'
    'heads/main/relays/online_relays_gps.csv'
)
TARGET = pathlib.Path(__file__).resolve().parent.parent / 'lib/src/bitchat/geo_relays.g.dart'

csv = urllib.request.urlopen(SOURCE, timeout=30).read().decode('utf-8')
assert csv.startswith('Relay URL,Latitude,Longitude'), 'unexpected header'
assert "'''" not in csv
TARGET.write_text(
    '// Generated by tool/update_bitchat_relays.py from bitchat\'s relay list;\n'
    '// do not edit.\n\n'
    '/// bitchat\'s relays by location, as bundled with this build.\n'
    "const String bitchatBundledGeoRelays = r'''\n" + csv.strip() + "\n''';\n"
)
print(f'{len(csv.splitlines()) - 1} relays written to {TARGET}')
